export const ADD_COUNTRY = 'ADD_COUNTRY';
export const SELECT_COUNTRY = 'SELECT_COUNTRY';
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';

export const FETCH_COUNTRIES_IN_PROGRESS = 'FETCH_COUNTRIES_IN_PROGRESS';
export const FETCH_COUNTRIES_SUCCEDED = 'FETCH_COUNTRIES_SUCCEDED';
export const FETCH_COUNTRIES_FAILED = 'FETCH_COUNTRIES_FAILED';

export const ADD_COUNTRY_IN_PROGRESS = 'ADD_COUNTRY_IN_PROGRESS';
export const ADD_COUNTRY_SUCCEDED = 'ADD_COUNTRY_SUCCEDED';
export const ADD_COUNTRY_FAILED = 'ADD_COUNTRY_FAILED';